name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - app/
  pull_request:
    branches: [ master ]
    paths:
      - app/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug
      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/raspio.apk
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.2
        with:
          name: debug-build
          path: app/app/build/outputs/apk/debug/raspio.apk