name: Update OpenAPI documentation

on:
  push:
    branches: [ dev ]
    paths:
      - api-specification.yaml
  workflow_dispatch:

jobs:
  copy-to-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: api-specification.yaml
          destination_repo: bickoSiTiEff/Raspio-Docs
          destination_branch: master
          user_email: noreply@github.com
          user_name: GitHub Actions
          commit_message: "Update API specification\n\nUpdate from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"