name: Shellcheck

on:
  push:
    paths:
      - setup/install.sh
      - .github/workflows/shellcheck.yml
  pull_request:
    paths:
      - setup/install.sh
      - .github/workflows/shellcheck.yml
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          scandir: './setup'